#ifndef MatrixBitmaps_h
#define MatrixBitmaps_h

#include <Arduino.h>

/**
 * @brief 8x8 TrueColor Bitmap Definitions
 * 
 * stored as linear arrays of 64 unint32_t values (0x00RRGGBB).
 * Row-major order (Top-left to Bottom-right).
 */
namespace MATRIX_ICONS {

    // Palette Helpers
    constexpr uint32_t COLOR_BLACK = 0x000000;
    constexpr uint32_t COLOR_RED   = 0xFF0000;
    constexpr uint32_t COLOR_GREEN = 0x00FF00;
    constexpr uint32_t COLOR_BLUE  = 0x0000FF;
    constexpr uint32_t COLOR_ORANGE= 0xFFA500;
    constexpr uint32_t COLOR_YELLOW= 0xFFFF00;
    constexpr uint32_t COLOR_WHITE = 0xFFFFFF;

    // Checkmark (Green)
    static const uint32_t INFO[64] = {
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK,
        COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK
    };

    // Warning (Yellow Exclamation Mark)
    static const uint32_t WARNING[64] = {
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,  COLOR_BLACK,  COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_YELLOW, COLOR_YELLOW, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK
    };
    
    // Critical (Bold Red X)
    static const uint32_t CRITICAL[64] = {
        COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,
        COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK,
        COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED,   COLOR_BLACK,
        COLOR_RED,   COLOR_RED,   COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_RED,   COLOR_RED
    };

} // namespace MATRIX_ICONS

#endif
