import js from '@eslint/js';
import ts from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import svelte from 'eslint-plugin-svelte';
import svelteParser from 'svelte-eslint-parser';
import prettier from 'eslint-config-prettier';
import security from 'eslint-plugin-security';
import globals from 'globals';

export default [
	// Ignore patterns (replaces .eslintignore)
	{
		ignores: [
			'node_modules/**',
			'build/**',
			'.svelte-kit/**',
			'package/**',
			'*.cjs',
			'src/lib/paraglide/**', // Auto-generated by Paraglide i18n
			'*.timestamp-*.mjs', // Vite generated files
			'coverage/**' // Test coverage report
		]
	},

	// JavaScript recommended rules
	js.configs.recommended,

	// Security rules
	{
		plugins: {
			security
		},
		rules: {
			...security.configs.recommended.rules,
			'security/detect-object-injection': 'off',
			'security/detect-unsafe-regex': 'off'
		}
	},

	// Base config for JS/TS files
	{
		files: ['**/*.{js,mjs,cjs,ts}'],
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: 'module',
			globals: {
				...globals.browser,
				...globals.es2017,
				...globals.node
			}
		}
	},

	// TypeScript files
	{
		files: ['**/*.{ts,tsx}'],
		languageOptions: {
			parser: tsParser
		},
		plugins: {
			'@typescript-eslint': ts
		},
		rules: {
			'no-undef': 'off',
			...ts.configs.recommended.rules,
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_'
				}
			],
			'@typescript-eslint/no-explicit-any': 'error'
		}
	},

	// Svelte files
	{
		files: ['**/*.svelte'],
		languageOptions: {
			parser: svelteParser,
			parserOptions: {
				parser: tsParser,
				extraFileExtensions: ['.svelte']
			},
			globals: {
				...globals.browser,
				...globals.es2017,
				...globals.node
			}
		},
		plugins: {
			svelte,
			'@typescript-eslint': ts
		},
		rules: {
			...svelte.configs.recommended.rules,
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_'
				}
			],
			'@typescript-eslint/no-explicit-any': 'error'
		}
	},

	// Prettier config (must be last to override other configs)
	prettier
];
